### ISSUE TITLE
UI improvement for CSS editing

### ISSUE THREAD

**Issue by ktsn** [ktsn/vue-designer#13]
The main goal of CSS editor in the preview is immediately synchronize the updates in the preview with the actual code. This is already achieved in #11, but it can be improved more in terms of UI.

I think Chrome devtool's CSS editor in the element inspector is really useful, so I would like to make vue-designer like that.

* [x] Change numeric value with up/down key. #70
* [ ] ~~Show completion list during editing prop/value.~~
* [x] Insert declaration to any position. #73
* [x] Focus next item when pressed the enter key. #71, #74 
* [x] Add a new declaration when finished editing the last declaration of a rule. #71 
* [x] Auto focus a new declaration #12

**Comment by ktsn** [comment]
> Show completion list during editing prop/value.

This seems quite time consuming and complex to implement, so I would leave it for now.
